### ISSUE TITLE
Please build exe

### ISSUE THREAD

**Issue by tyeeman** [ishani/Vanity#1]
Yes, I would like to try this out. Your site looks great!

**Comment by ishani** [comment]
I've put a quick release together for you, although this isn't particularly tested - I imagined anyone wanting to use it would want to go tinker a bit with the layout and code to customise it for their own needs.

However, it should get you some way towards being able to produce a gallery site. 

https://github.com/ishani/Vanity/releases/tag/alpha.1

**Comment by tyeeman** [comment]
Great, much appreciated!

**Comment by tyeeman** [comment]
Just getting back to this. It's working good but can I use it on a static server only, like github pages or netlify? I see there is a file called .htaccess which is not used by static site only companies.

**Comment by tyeeman** [comment]
Update - Yes works fine on Netlify. One thing I'm noticing is that when viewing all the images of one gallery on the page, they are shown vertically (in columns), not horizontally (rows), ie. image 2 is below image 1, etc. Is there an easy way to make them into rows instead of columns?

**Comment by ishani** [comment]
the .htaccess is optional, it just sets up some caching and basic filtering. You should be able to use the results on a completely static serving endpoint.

Not sure why it would only display one column; the same code generates https://photography.ishani.org/ and it has the expected 'masonry' style display.

Do you have a site uploaded I can look at? Perhaps there is an error in a JS library loading or something in the developer console we can examine to see why it's not behaving

**Comment by tyeeman** [comment]
There are 3 columns but the images are in columns, not rows. Like image1 is top left, image2 is below it, image3 is below image2, etc. Normally images are across from each other, ie. image2 is to the right of image1, image3 is to the right of image2, etc until that row ends and the next row begins. I could give a link but since your app renames all images you can't see their original order and where they are placed.

**Comment by ishani** [comment]
Ah I see - yes, this is a limitation / by-design of how Bootstrap does card masonry. The 'fix' is to use a different layout library like https://packery.metafizzy.co/ or http://bricklayer.js.org/ or https://masonry.desandro.com/

I might look at that in the future

**Comment by tyeeman** [comment]
Thanks for considering it!
